## 第二章 NumPy入门

用`np`别名导入Numpy

In [4]:
import numpy as np

使用`np.array`从Python列表创建数组

In [5]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Numpy要求数组必须包含同一类型的数据。如果类型不匹配，Numpy将会向上转换（如果可行）

In [6]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

如果明确希望设置数组的数据类型，可以用`dtype`关键字

In [7]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

创建一个长度为10的数组，数组的值都是0

In [8]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

创建一个3×5的浮点型数组，数组的值都是1

In [9]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

创建一个3×5的浮点型数组，数组的值都是3.14

In [10]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

创建一个3×5的浮点数数组，数组的值是一个线性序列  
从0开始，到20结束，步长为2

In [11]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

创建一个5个元素的数组，这5个数均匀地分配到0～1

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

创建一个3×3的、在0～1均匀分布的随机数组成的数组

In [13]:
np.random.random((3, 3))

array([[0.45436855, 0.87153684, 0.86977774],
       [0.65032073, 0.37235359, 0.49562706],
       [0.10790527, 0.02730223, 0.93362776]])

创建一个3×3的、均值为0、方差为1的正太分布的随机数数组

In [14]:
np.random.normal(0, 1, (3, 3))

array([[-0.63039866,  0.76238746,  0.23795611],
       [ 0.77604032,  0.43207329, -1.11674647],
       [-1.22373789,  0.45224834, -0.056798  ]])

创建一个3×3的、[0, 10]区间的随机整型数组

In [15]:
np.random.randint(0, 10, (3, 3))

array([[4, 4, 6],
       [4, 1, 1],
       [7, 1, 9]])

创建一个3×3的单位矩阵

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

创建一个由3个整型数组成的未初始化的数组  
数组中的值是任意值

In [17]:
np.empty(3)

array([1., 1., 1.])

每个数组都有如下属性：
- `nidm`：数组的维度
- `shape`：数组每个维度的大小
- `size` 数组的总大小
- `dtype` 数组的数据类型
- `itemsize` 每个数组元素字节大小
- `nbytes` 数组总字节大小  

一般来说，可以认为`nbytes`与`itemsize`和`size`的乘积大小相等

In [18]:
np.random.seed(0) # 设置随机数种子

x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3, 4)) # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组

print(x2)
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size:", x2.size)
print("x2 itemsize:", x2.itemsize)
print("x2 nbytes", x2.nbytes)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x2 ndim: 2
x2 shape: (3, 4)
x2 size: 12
x2 itemsize: 8
x2 nbytes 96


一维数组获取单个元素

In [19]:
print(x1)
print(x1[0]) # 获取第一个元素
print(x1[-1]) # 获取最后一个元素

[5 0 3 3 7 9]
5
9


二维数组获取单个元素

In [20]:
print(x2)
print(x2[0, 0])
print(x2[2, -1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
7


注意⚠️：NumPy数组是固定类型的，如果将一个浮点数插入到一个整型数组中，浮点值将会被截断，并且不会有任何提示

In [21]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

#### 2.2.3 数组切片  
语法：`x[start:stop:step]`  
`start`默认值为`0`  
`stop`默认为维度的大小  
`step`默认值为`1`

数组切片返回的是数组的视图，而不是数据的副本，修改子数组，原始数组也会被修改

**一维数组**

In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[:5] # 前5个元素

array([0, 1, 2, 3, 4])

In [24]:
x[5:] # 索引5之后的元素

array([5, 6, 7, 8, 9])

In [25]:
x[4:7] #索引4到索引7之间的元素（含头不含尾）

array([4, 5, 6])

In [26]:
x[::2] # 隔一个元素

array([0, 2, 4, 6, 8])

In [27]:
x[1::2] # 隔一个元素，从索引1开始

array([1, 3, 5, 7, 9])

In [28]:
x[::-1] # 所有元素逆序

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
x[5::-2] # 从索引5开始每隔一个元素逆序

array([5, 3, 1])

**多维数组**

In [30]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [31]:
x2[:2, :3] # 两行，三列

array([[3, 5, 2],
       [7, 6, 8]])

In [32]:
x2[:3, ::2] # 所有行，每隔一列

array([[3, 2],
       [7, 8],
       [1, 7]])

In [33]:
x2[::-1, ::-1] # 逆序

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

**获取数组的行与列**

In [34]:
x2[:, 0] # x2的第一列

array([3, 7, 1])

`:`表示空切片

In [35]:
x2[0, :] # x2的第一行
# x2[0] 等效

array([3, 5, 2, 4])

**创建数组的副本**

In [37]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[3 5]
 [7 6]]


**数组的变形**

In [40]:
# 原数组的大小必须与变形后数组的大小一致
np.arange(1, 10).reshape((3, 3)) # 3×3的矩阵

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [44]:
# 通过变形获得的行向量
x.reshape((1, 3))

array([[1, 2, 3]])

In [45]:
# 通过newaxis获得的行向量
x[np.newaxis, :]

array([[1, 2, 3]])

In [46]:
# 通过变量获得的列向量
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [47]:
# 通过newaxis获得的列向量
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

**数据的拼接**

In [49]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [52]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid]) # 沿着第一个轴拼接

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.concatenate([grid, grid], axis = 1) # 沿着第二个轴拼接（从0开始索引）

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

沿着固定维度处理数组时，下面的方式更简洁

In [55]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid]) # 垂直栈数组

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [57]:
y = np.array([[99],
              [99]])
np.hstack([grid, y]) # 水平栈数组

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

**数组的分裂**

In [62]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # [3, 5]表示分裂点的位置
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [64]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [67]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#### 2.3.3 探索Numpy的通用函数

In [68]:
# 地板除法
3 // 2

1

In [73]:
# 指数运算
2 ** 3

8

In [70]:
# 绝对值
np.abs(-2)

2

In [71]:
# 复数是由一个实数和一个虚数组合构成，表示为：x+yj
# 一个复数是一对有序浮点数(x,y)，其中x是实数部分，y是虚数部分。
np.abs(3 - 4j) # 返回的是复数的幅度

5.0

In [76]:
# e^x
np.exp(2)

7.38905609893065

In [78]:
# 2^x
np.exp2(4)

16.0

In [79]:
# x^y
np.power(3, 3)

27

In [80]:
# ln(x)
np.log(4)

1.3862943611198906

In [82]:
# log2(x)
np.log2(4)

2.0

In [83]:
# log10(x)
np.log10(10)

1.0

**聚合**

In [90]:
x = np.arange(1, 6)
np.add.reduce(x) # 返回相加后的结果

15

In [88]:
np.multiply.reduce(x) # 返回相乘后的结果

120

In [92]:
np.add.accumulate(x) # 存储每次计算的中间结果

array([ 1,  3,  6, 10, 15])

In [94]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

**外积**  
任何通用函数都可以用`outer`方法获得两个不同输入数组所有元素对的函数运算结果

In [95]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

**数组值求和**

In [102]:
L = np.random.random(100)
print(sum(L)) # Python内置函数
print(np.sum(L)) # Numpy的sum函数在编译码中执行，速度稍快

48.561082284279706
48.56108228427973


**最大值和最小值**

In [100]:
big_array = np.random.rand(100)
# 内置函数
print(min(big_array))
print(max(big_array))

0.004048106368426341
0.9850322788832359


**多维度聚合**

In [106]:
M = np.random.random((3, 4))
print(M)

[[0.97957325 0.14847809 0.25870232 0.21552881]
 [0.5799124  0.97575169 0.2730089  0.97007507]
 [0.02549735 0.88804371 0.70860884 0.27777367]]


In [107]:
# 默认情况下，每个NumPy聚合函数将会返回对整个数组的聚合结果
M.sum()

6.300954098173474

In [109]:
# 找出每一行的最小值
M.min(axis=0)

array([0.02549735, 0.14847809, 0.25870232, 0.21552881])

In [111]:
# 找出每一列的最大值
M.max(axis=1)

array([0.97957325, 0.97575169, 0.88804371])

### 2.5 数组的计算：广播

In [113]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [114]:
a + 5

array([5, 6, 7])

In [115]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [116]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 2.5.2 广播的规则

In [117]:
M = np.ones((2, 3))
a = np.arange(3)
print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [118]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])